# Name of the workflow as it will appear in the GitHub Actions dashboard
name: Fuzz Testing

# Trigger the workflow
on:
  # Trigger the workflow using a cron schedule
  schedule:
    # the workflow will run at 12:00 PM every Monday
    - cron: '0 12 * * 1'  

  # Run the workflow on pushes to the 'main' branch
  push:
    branches:
      - main

  # Run the workflow on pull requests targeting the 'main' branch
  pull_request:
    branches:
      - main
  
  # Allows manual triggering of the workflow
  workflow_dispatch: 

jobs:
  test-fuzz:
    # The type of machine that the job will run on (Ubuntu in this case)
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3  

    # Step 2: Set up Go environment
    - name: Set up Go
      uses: actions/setup-go@v3  
      with:
        go-version: '1.23.2'

    # Step 3: Run the fuzz tests
    - name: Run Fuzz Tests
      # runs all tests in the current directory and all subdirectories
      # -v logs into the console
      run: go test -v ./...  

    # Step to upload the fuzz test report as an artifact
    - name: Upload Fuzz Test Report
      # Ensure this step runs even if the tests fail
      if: always()  
      uses: actions/upload-artifact@v4  # Upload the report as an artifact
      with:
        name: fuzz-test-report  # Name of the artifact
        path: fuzz_test_report.txt  # Path to the report file
