# Name of the workflow as it will appear in the GitHub Actions dashboard
name: Fuzz Testing

# Trigger the workflow
on:
  # Trigger the workflow using a cron schedule
  schedule:
    # the workflow will run at 12:00 PM every Monday
    - cron: '0 12 * * 1'  

  # Run the workflow on pushes to the 'main' branch
  push:
    branches:
      - main
      - chloe

  # Run the workflow on pull requests targeting the 'main' branch
  pull_request:
    branches:
      - main
      - chloe
    
  # Allows manual triggering of the workflow
  workflow_dispatch: 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: Build and Run Docker Compose
        run: |
          docker-compose -f docker-compose.generated.yml up --abort-on-container-exit

      - name: Upload Test Reports
        uses: actions/upload-artifact@v3
        with:
          name: test_reports
          path: output/

      - name: Upload Logs
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: logs/